"""Web application firewall / CDN detection.

Best-effort: looks at response headers and body markers. The presence of a WAF
doesn't block scanning, but is recorded in the report and used to lower the
intensity of aggressive enumeration.
"""

from __future__ import annotations

import httpx

# (label, header_name, header_substring) — case-insensitive
_HEADER_SIGNATURES: tuple[tuple[str, str, str], ...] = (
    ("Cloudflare", "server", "cloudflare"),
    ("Cloudflare", "cf-ray", ""),
    ("Cloudflare", "cf-cache-status", ""),
    ("Sucuri", "server", "sucuri"),
    ("Sucuri", "x-sucuri-id", ""),
    ("Wordfence", "x-wf-id", ""),
    ("Akamai", "server", "akamaighost"),
    ("Akamai", "x-akamai-transformed", ""),
    ("Imperva", "x-iinfo", ""),
    ("Incapsula", "x-cdn", "incapsula"),
    ("Fastly", "x-served-by", "cache-"),
    ("Fastly", "fastly-debug-digest", ""),
    ("Nginx Plus / ModSecurity", "x-mod-security", ""),
    ("AWS CloudFront", "via", "cloudfront"),
    ("AWS CloudFront", "x-amz-cf-id", ""),
    ("Google Cloud Armor", "server", "googlefrontend"),
    ("BunnyCDN", "server", "bunnycdn"),
    ("Bitninja", "x-bitninja-protected", ""),
    ("SiteGround", "x-proxy-cache", ""),
    ("WP Engine", "x-cacheable", "shortlived"),
)

_BODY_SIGNATURES: tuple[tuple[str, str], ...] = (
    ("Sucuri", "sucuri website firewall"),
    ("Cloudflare", "checking your browser before accessing"),
    ("Cloudflare", "attention required! | cloudflare"),
    ("Wordfence", "generated by wordfence"),
    ("Akamai", "reference&#32;&#35;"),
)


def detect_from_response(response: httpx.Response) -> str | None:
    """Return the first matching WAF label, or None."""
    headers = {k.lower(): v.lower() for k, v in response.headers.items()}
    for label, name, needle in _HEADER_SIGNATURES:
        val = headers.get(name.lower())
        if val is None:
            continue
        if needle == "" or needle.lower() in val:
            return label

    try:
        body = response.text.lower()[:8192]
    except (UnicodeDecodeError, httpx.ResponseNotRead):
        body = ""
    for label, needle in _BODY_SIGNATURES:
        if needle in body:
            return label
    return None
